{{- if .Values.monitoring.prometheus.enabled -}}
apiVersion: v1
kind: PersistentVolume
metadata:
    name: "{{ .Release.Name }}--sentry-persistence--pv"
spec:
    storageClassName: "standard"
    capacity:
        storage: {{ .Values.sentry.persistence.size }}
    accessModes:
        - {{ .Values.sentry.persistence.accessMode }}
    claimRef:
        namespace: default
        name: "{{ .Values.sentry.persistence.existingClaim }}"
        {{- if .Values.dev }}
    hostPath:
        path: /tmp/sentry
        {{ else }}
    gcePersistentDisk:
        pdName: {{ .Values.monitoring.sentry.persistence.gceVolume }}
        fsType: {{ .Values.monitoring.sentry.persistence.gceVolumeType }}
        {{ end }}
{{- end -}}