apiVersion: v1
kind: Secret
metadata:
  name: {{ template "ingress.fullname" . }}--clouddns-service-account-key--sec
  namespace: {{ .Release.Namespace }}
  labels:
    name: {{ template "ingress.fullname" . }}--clouddns-service-account-key--sec
    chart: {{ .Chart.Name }}
data:
  key.json: {{ .Values.clouddns.key }}
