apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
  name: {{ include "ingress.fullname" . }}--cluster-issuer
  labels:
    name: {{ include "ingress.fullname" . }}--ingress
    chart: {{ .Chart.Name }}
spec:
  acme:
    server: {{ .Values.issuer.server }}
    email: {{ .Values.issuer.email }}
    privateKeySecretRef:
      name: {{ include "ingress.fullname" . }}--issuer-key--secret
    solvers:

      # example: cross-account zone management for example.com
      # this solver uses ambient credentials (i.e. inferred from the environment or EC2 Metadata Service)
      # to assume a role in a different account
      - selector:
          {{ if eq .Values.domainExtension "" }}
          dnsZones:
            - "{{ .Values.baseDomain }}"
            - "*.{{ .Values.baseDomain }}"
          {{ else }}
          dnsZones:
            - "{{ .Values.domainExtension }}.{{ .Values.baseDomain }}"
            - "*.{{ .Values.domainExtension }}.{{ .Values.baseDomain }}"
          {{ end }}
        dns01:
          route53:
            region: {{ .Values.route53.region }}
            accessKeyID: {{ .Values.route53.keyId }}
            secretAccessKeySecretRef:
              name: route53-credentials--sec
              key: password.txt
