apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: {{ include "ingress.fullname" . }}--wildcard-certificate--cert
  labels:
    name: {{ include "ingress.fullname" . }}--wildcard-certificate--cert
    chart: {{ .Chart.Name }}
spec:
  secretName: {{ include "ingress.fullname" . }}--wildcard-certificate--sec
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - "*.{{ .Values.domainExtension }}.{{ .Values.baseDomain }}"
