export type TxType =
    | 'adjustment'
    | 'advance'
    | 'advance_funding'
    | 'application_fee'
    | 'application_fee_refund'
    | 'charge'
    | 'connect_collection_transfer'
    | 'issuing_authorization_hold'
    | 'issuing_authorization_release'
    | 'issuing_transaction'
    | 'payment'
    | 'payment_failure_refund'
    | 'payment_refund'
    | 'payout'
    | 'payout_cancel'
    | 'payout_failure'
    | 'refund'
    | 'refund_failure'
    | 'reserve_transaction'
    | 'reserved_funds'
    | 'stripe_fee'
    | 'stripe_fx_fee'
    | 'tax_fee'
    | 'topup'
    | 'topup_reversal'
    | 'transfer'
    | 'transfer_cancel'
    | 'transfer_failure'
    | 'transfer_refund';

export const TxTypeColors = {
    adjustment: 'normal',
    advance: 'normal',
    advance_funding: 'normal',
    application_fee: 'normal',
    application_fee_refund: 'error',
    charge: 'normal',
    connect_collection_transfer: 'normal',
    issuing_authorization_hold: 'normal',
    issuing_authorization_release: 'normal',
    issuing_transaction: 'normal',
    payment: 'normal',
    payment_failure_refund: 'error',
    payment_refund: 'error',
    payout: 'normal',
    payout_cancel: 'error',
    payout_failure: 'error',
    refund: 'normal',
    refund_failure: 'error',
    reserve_transaction: 'normal',
    reserved_funds: 'normal',
    stripe_fee: 'normal',
    stripe_fx_fee: 'normal',
    tax_fee: 'normal',
    topup: 'normal',
    topup_reversal: 'error',
    transfer: 'normal',
    transfer_cancel: 'error',
    transfer_failure: 'error',
    transfer_refund: 'error',
};
