apiVersion: v1
kind: Service
metadata:
  name: {{ include "ingress.fullname" . }}--nginx-ingress--svc
  labels:
    name: {{ include "ingress.fullname" . }}--nginx-ingress--svc
    chart: {{ .Chart.Name }}
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "tcp"
    service.beta.kubernetes.io/aws-load-balancer-proxy-protocol: "*"
    {{ if eq .Values.domainExtension "" }}
    external-dns.alpha.kubernetes.io/hostname: "*.{{ .Values.baseDomain }}"
    {{ else }}
    external-dns.alpha.kubernetes.io/hostname: "*.{{ .Values.domainExtension }}.{{ .Values.baseDomain }}"
    {{ end }}
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  - port: 443
    targetPort: 443
    protocol: TCP
    name: https
  selector:
    app: {{ include "ingress.fullname" . }}--nginx-ingress--app
