apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "platform.fullname" . }}--server--pvc
  labels:
    name: {{ include "platform.fullname" . }}--server--pvc
    chart: {{ .Chart.Name }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: aws-efs

