apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "platform.fullname" . }}--server--hpa
  labels:
    name: {{ include "platform.fullname" . }}--server--hpa
    chart: {{ .Chart.Name }}
spec:
  maxReplicas: 10
  minReplicas: 2
  scaleTargetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: {{ include "platform.fullname" . }}--server--sfs
  targetCPUUtilizationPercentage: 80
